package:
  name: ibis-framework
  version: "0.8.1"

source:
  fn: ibis-framework-0.8.1.tar.gz
  url: https://pypi.io/packages/source/i/ibis-framework/ibis-framework-0.8.1.tar.gz
  md5: 18cda0ac0d0f7fc2d69798ca7ed0300d

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest
    - numpy >=1.7.0
    - pandas >=0.12.0
    - impyla >=0.13.8
    - python-hdfs >=2.0.0
    - sqlalchemy >=1.0.0
    - six
    - mock  # [py<35]

  run:
    - python
    - pytest
    - numpy >=1.7.0
    - pandas >=0.12.0
    - impyla >=0.13.8
    - python-hdfs >=2.0.0
    - sqlalchemy >=1.0.0
    - six
    - toolz
    - mock  # [py<35]

test:
  imports:
    - ibis
    - ibis.expr
    - ibis.expr.tests
    - ibis.hive
    - ibis.hive.tests
    - ibis.impala
    - ibis.impala.tests
    - ibis.spark
    - ibis.spark.tests
    - ibis.sql
    - ibis.sql.presto
    - ibis.sql.presto.tests
    - ibis.sql.redshift
    - ibis.sql.redshift.tests
    - ibis.sql.sqlite
    - ibis.sql.sqlite.tests
    - ibis.sql.tests
    - ibis.sql.vertica
    - ibis.sql.vertica.tests
    - ibis.tests

about:
  license: Apache 2.0
  home: http://www.ibis-project.org
  summary: 'Productivity-centric Python Big Data Framework'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
