{% set version = "12.0.0" %}

package:
  name: ibis-framework
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ibis-framework/ibis_framework-{{ version }}.tar.gz
  sha256: 238624f2c14fdab8382ca2f4f667c3cdb81e29844cd5f8db8a325d0743767c61

build:
  number: 0
  skip: true  # [py<310]
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - atpublic >=2.3
    - parsy >=2
    - python-dateutil >=2.8.2
    - sqlglot >=23.4,!=26.32.0
    - toolz >=0.11
    - typing-extensions >=4.3.0
    - python-tzdata >=2022.7
  run_constrained:
    - PyAthena >=3.11.0
    - pyarrow >=10.0.1
    - pyarrow-hotfix >=0.4
    - numpy >=1.23.2,<3
    - pandas >=1.5.3,<4
    - rich >=12.4.4
    - fsspec

test:
  requires:
    - pip
  imports:
    - ibis
  commands:
    - pip check

about:
  home: https://ibis-project.org
  dev_url: https://github.com/ibis-project/ibis
  doc_url: https://ibis-project.org
  license: Apache-2.0
  license_family: Apache
  summary: The portable Python dataframe library

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
