{% set version = "12.0.0" %}

package:
  name: ibis-framework
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ibis-framework/ibis_framework-{{ version }}.tar.gz
  sha256: 238624f2c14fdab8382ca2f4f667c3cdb81e29844cd5f8db8a325d0743767c61

build:
  number: 0
  skip: true  # [py<310]
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - atpublic >=2.3
    - parsy >=2
    - python-dateutil >=2.8.2
    - sqlglot >=23.4,!=26.32.0
    - toolz >=0.11
    - typing-extensions >=4.3.0
    - python-tzdata >=2022.7
  run_constrained:
    - pyathena >=3.11.0
    - pyarrow >=10.0.1
    - pyarrow-hotfix >=0.4
    - numpy >=1.23.2,<3
    - pandas >=1.5.3,<4
    - rich >=12.4.4
    - db-dtypes >=0.3
    - google-cloud-bigquery >=3
    - google-cloud-bigquery-storage >=2
    - pydata-google-auth >=1.4.0
    - pandas-gbq >=0.26.1
    - clickhouse-connect >=0.5.23
    - databricks-sql-connector >=4
    - datafusion >=0.6
    - packaging >=21.3
    - pydruid >=0.6.7
    - duckdb >=0.10.3,!=1.3.0
    - pyexasol >=0.25.2
    - impyla >=0.17
    - pyodbc >=4.0.39
    - mysqlclient >=2.2.4
    - psycopg >=3.2.0
    - oracledb >=1.3.1
    - polars >=1
    - pyspark >=3.5,<4.1
    - singlestoredb >=1.0
    - parsimonious >=0.11.0
    - snowflake-connector-python >=3.0.2,!=3.3.0b1
    - regex >=2021.7.6
    - psycopg2 >=2.8.4
    - trino >=0.321
    - graphviz >=0.16
    - black >=22.1.0
    - deltalake >=0.9.0
    - pins >=0.8.3
    - geoarrow-types >=0.2
    - geopandas >=0.6
    - pyproj >=3.3.0
    - shapely >=2

test:
  requires:
    - pip
  imports:
    - ibis
  commands:
    - pip check

about:
  home: https://ibis-project.org
  dev_url: https://github.com/ibis-project/ibis
  doc_url: https://ibis-project.org
  license: Apache-2.0
  license_family: Apache
  summary: The portable Python dataframe library

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
