{% set version = "1.4.0" %}

package:
  name: ibis-framework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ibis-framework/ibis-framework-{{ version }}.tar.gz
  md5: d42c818fb6548ab48f9dd4be99b46c4b

build:
  number: 0
  skip: True  # [ppc64le and py==27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - clickhouse-driver >=0.1.3
    - clickhouse-cityhash  # [not win]
    - clickhouse-sqlalchemy
    - geoalchemy2
    - geopandas
    - google-cloud-bigquery-core >=1.12.0,<1.24.0dev
    - graphviz
    - impyla >=0.15.0
    - lz4
    - multipledispatch >=0.6
    - numpy >=1.15
    - pandas >=0.25.3
    - psycopg2
    - pyarrow >=0.15
    - pydata-google-auth
    - pymapd 0.24  # [py<38]
    - pymysql
    - pyspark >=2.4.3
    - pytables >=3.0.0
    - python
    - python-graphviz
    - python-hdfs >=2.0.16
    - pytz
    - regex
    - requests
    - shapely
    - setuptools
    - sqlalchemy >=1.1
    - thrift >=0.11
    - thriftpy2
    - toolz

test:
  requires:
    - pytest >=3
    - mock  # [py27]
  imports:
    - ibis
    - ibis.backends.bigquery
    - ibis.backends.clickhouse
    - ibis.backends.csv
    - ibis.backends.parquet
    - ibis.backends.hdf5
    - ibis.backends.impala
    - ibis.backends.mysql
    - ibis.backends.omniscidb  # [py<38]
    - ibis.backends.pandas
    - ibis.backends.postgres
    - ibis.backends.pyspark
    - ibis.backends.spark
    - ibis.backends.sqlite

about:
  license: Apache 2.0
  home: http://www.ibis-project.org
  summary: 'Productivity-centric Python Big Data Framework'

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
