travis:
  secure:
    BINSTAR_TOKEN: iZQcygOJdGfE/dGQGLEW9+oVoOyJe2qod7FGZWQD6Sw3eh508AGSlp22vjmTmriX8pu9ocUo2NZft+5i93/ArSvhHrzE13vMjzVBLVbtbmNsBDWHtYPZM6Zt8JovW4M8s9GgQUVqscMYfxYizRWHsw2U4fAfdzCKbgk3xzRoQeBLFkqEWph808Sc7FGF5DPEGqOP0+Xl3xDj/qzagZ9NAPiwoBRqzSub989pVCubie0MRE55bhQdJDC4YJIHqq7ydgjMPmNMGWf5AAYaDl+RxLXtRTFX/qs9OBTNBNj7kP1BGTPnTaYIRX0W3JyBA7ogZBSkKnXFmcJiee49+TXuASnnmWsa2YxVvaA+O7iGS2VQbzLKt+ibOez9pcb8Y7UuQheUWoRgPYwZEgCyvXvSDDDrDMEyQosLKUiu9g0e4zGbkEUhamRTZrTQebC1FuzsPPr8AiaCsNQx8TQzRlJSAkFZQkbaKdyWH1phaDLOA64Hpab8NP39uHqqg37rxtwdQn0+E2fIAl4szSDjylJqI6xmtoNlXd8m0ytWZlrJ3oSAnvfQ8P5IHO/k4BkC+Gdwzipm6O54LcO34FXAlPIjsM0u7QgjGBLBVa6g+Bss6FfVZLge0gcLg3Of5SDd5xmLZqDs6N/QGlxDhZYlfVIlw2nXQYRbJm3rq2qlbJ5SQYk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
